services:
  mongodb:
    image: mongo:latest
    container_name: webmud-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart:
      unless-stopped

  mqtt:
    image: eclipse-mosquitto:latest
    container_name: webmud-mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./event-bus/mqtt-config:/mosquitto/config:rw
      - ./event-bus/mqtt-data:/mosquitto/data:rw
      - ./event-bus/mqtt-log:/mosquitto/log:rw
    restart: 
      unless-stopped

  # auth-service:
  #   build:
  #     context: ./auth-service
  #   container_name: webmud-auth-service
  #   ports:
  #     - "3005:3005"
  #   environment:
  #     - AZURE_B2C_TENANT_NAME=${AZURE_B2C_TENANT_NAME}
  #     - AZURE_B2C_USER_FLOW=${AZURE_B2C_USER_FLOW}
  #     - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
  #     - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  #   depends_on:
  #     - mongodb

  character-service:
    build:
      context: ./character-service
    container_name: webmud-character-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

volumes:
  mongo-data:
  config:
  data:
  log:
