services:
  mongodb:
    image: mongo:latest
    container_name: webmud-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo-data:/data/db
    restart:
      unless-stopped

  redis:
    image: redis:latest
    container_name: webmud-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  

  # mqtt:
  #   image: eclipse-mosquitto:latest
  #   container_name: webmud-mqtt
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./event-bus/mqtt-config:/mosquitto/config:rw
  #     - ./event-bus/mqtt-data:/mosquitto/data:rw
  #     - ./event-bus/mqtt-log:/mosquitto/log:rw
  #   restart: 
  #     unless-stopped

  # auth-service:
  #   build:
  #     context: ./auth-service
  #   container_name: webmud-auth-service
  #   ports:
  #     - "3005:3005"
  #   environment:
  #     - AZURE_B2C_TENANT_NAME=${AZURE_B2C_TENANT_NAME}
  #     - AZURE_B2C_USER_FLOW=${AZURE_B2C_USER_FLOW}
  #     - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
  #     - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
  #   depends_on:
  #     - mongodb

  # character-service:
  #   build:
  #     context: ./character-service
  #   container_name: webmud-character-service
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - mongodb
  #     - mqtt
  
  # game-service:
  #   build:
  #     context: ./game-service
  #   container_name: webmud-game-service
  #   ports:
  #     - "28999:28999"
  #   depends_on:
  #     - mongodb
  #     - mqtt

volumes:
  mongo-data:
  config:
  data:
  log:
  redis-data:
