services:
  mongodb:
    image: mongo:latest
    container_name: webmud-mongodb
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - "27017:27017"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'localhost:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo-data:/data/db
    restart:
      unless-stopped
    networks:
      default:
        aliases:
          - mongodb

  # redis:
  #   image: redis:latest
  #   container_name: webmud-redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis-data:/data
  #   restart: unless-stopped
  #   networks:
  #     default:
  #       aliases:
  #         - redis

  # webmud_client:
  #   image: saitcho/webmud_client:latest
  #   container_name: webmud-client
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./webmud_client/.env
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/?directConnection=true&replicaSet=rs0
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     - mongodb
  #     - redis
  #   networks:
  #     default:
  
  # game_service:
  #   image: saitcho/game_service:latest
  #   container_name: game-service
  #   ports:
  #     - "28999:28999"
  #   env_file:
  #     - ./game_service/.env
  #   environment:
  #     - MONGODB_URI=mongodb://mongodb:27017/?directConnection=true&replicaSet=rs0
  #     - REDIS_URL=redis://redis:6379
  #   depends_on:
  #     mongodb:
  #       condition: service_healthy
  #     redis: 
  #       condition: service_started
  #   networks:
  #     - default
  
  # nginx:
  #   image: nginx:latest
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: always
  #   volumes:
  #     - ./nginx/conf/:/etc/nginx/conf.d/:ro
  #     - ./certbot/www/:/var/www/certbot/:ro
  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

  # mqtt:
  #   image: eclipse-mosquitto:latest
  #   container_name: webmud-mqtt
  #   ports:
  #     - "1883:1883"
  #   volumes:
  #     - ./event-bus/mqtt-config:/mosquitto/config:rw
  #     - ./event-bus/mqtt-data:/mosquitto/data:rw
  #     - ./event-bus/mqtt-log:/mosquitto/log:rw
  #   restart: 
  #     unless-stopped

volumes:
  mongo-data:
  config:
  data:
  log:
  redis-data:

networks:
  default:
    driver: bridge
