services:
  mongodb:
    image: mongo:latest
    container_name: webmud-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  auth-service:
    build:
      context: ./auth-service
    container_name: webmud-auth-service
    ports:
      - "3005:3005"
    environment:
      - AZURE_B2C_TENANT_NAME=${AZURE_B2C_TENANT_NAME}
      - AZURE_B2C_USER_FLOW=${AZURE_B2C_USER_FLOW}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
    depends_on:
      - mongodb

  character-service:
    build:
      context: ./character-service
    container_name: webmud-character-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  
  web-client:
    build:
      context: ./web-client
    container_name: webmud-web-client
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - character-service

volumes:
  mongo-data:
