openapi: "3.0.0"
info:
  title: "MUD Mob API"
  version: "1.0.0"
paths:
  /mobs:
    get:
      summary: "Get all mobs"
      operationId: getMobs
      responses:
        '200':
          description: "A list of mobs"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Mob"
  /mobs/{id}:
    get:
      summary: "Get a mob by ID"
      operationId: getMobById
      parameters:
        - name: "id"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        '200':
          description: "A single mob"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Mob"
components:
  schemas:
    Mob:
      type: "object"
      properties:
        id:
          type: "integer"
        name:
          type: "string"
        description:
          type: "string"
        level:
          type: "integer"
        health:
          type: "object"
          properties:
            max:
              type: "integer"
            current:
              type: "integer"
        attack:
          type: "object"
          properties:
            min:
              type: "integer"
            max:
              type: "integer"
        defense:
          type: "integer"
        experience:
          type: "integer"
        loot:
          type: "array"
          items:
            type: "object"
            properties:
              item_id:
                type: "integer"
              chance:
                type: "number"
                format: "float"
        behaviors:
          type: "array"
          items:
            type: "object"
            properties:
              type:
                type: "string"
              trigger:
                type: "string"