name: Request Copilot Review

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read
  pull-requests: write

jobs:
  request-copilot-review:
    runs-on: ubuntu-latest
    name: Request GitHub Copilot Review
    
    steps:
      - name: Request Copilot Review
        uses: actions/github-script@v7
        with:
          script: |
            // Request a Copilot review on the PR
            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              reviewers: [],
              team_reviewers: []
            });
            
            // Add a comment mentioning Copilot
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `@github-copilot review`
            });
