name: webmud_client Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  buildPush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./webmud_client/ --file ./webmud_client/Dockerfile --tag saitchocr.azurecr.io/webmud_client:$(date +%s)

    - name: Push the Docker image
      run: docker push saitchocr.azurecr.io/webmud_client:$(date +%s)

