name: vite_client Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'vite_client/**'
      - '.github/workflows/docker-image-client.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'vite_client/**'
      - '.github/workflows/docker-image-client.yml'

jobs:
  buildPush:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set tag
      id: set_tag
      run: |
        if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          echo "tag=latest" >> $GITHUB_OUTPUT
        else
          echo "tag=$(date +%s)-${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        fi

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.REGISTRY_SECRET }}" | docker login saitchocr.azurecr.io -u saitchocr --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./vite_client
        file: ./vite_client/Dockerfile
        push: true
        tags: saitchocr.azurecr.io/vite_client:${{ steps.set_tag.outputs.tag }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

