name: webmud_client Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  buildPush:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set tag
      id: set_tag
      run: echo "tag=$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build the Docker image
      run: docker build ./webmud_client/ --file ./webmud_client/Dockerfile --tag saitchocr.azurecr.io/webmud_client:${{ steps.set_tag.outputs.tag }}

    - name: Log in to Azure Container Registry
      run: az acr login --name saitchocr --username saitchocr --password ${{ secrets.REGISTRY_SECRET }}

    - name: Push the Docker image
      run: docker push saitchocr.azurecr.io/webmud_client:${{ steps.set_tag.outputs.tag }}

